In [126]:
import cv2
import numpy as np
import random
import matplotlib.pyplot as plt
import pickle
import os

In [127]:
DATADIR = os.path.join('D:\Datasets\PetImages')
CATEGORIES = ['Dog', 'Cat']
IMG_SIZE = 75

In [128]:
def CREATE_TRAINING_DATA():    
    for category in CATEGORIES:
        PATH = os.path.join(DATADIR,category)
        CLASS_NUM = CATEGORIES.index(category)
        for IMG in os.listdir(PATH):
            try:
                IMG_ARRAY = cv2.imread(os.path.join(PATH,IMG), cv2.IMREAD_GRAYSCALE)
                NEW_ARRAY = cv2.resize(IMG_ARRAY, (IMG_SIZE, IMG_SIZE))
                TRAINING_DATA.append([NEW_ARRAY, CLASS_NUM])
            except Exception as e:
                pass

In [129]:
TRAINING_DATA = []
CREATE_TRAINING_DATA()
random.shuffle(TRAINING_DATA)

In [130]:
CREATE_TRAINING_DATA()
random.shuffle(TRAINING_DATA)

In [131]:
X = []
y = []

In [132]:
for element in TRAINING_DATA:
    X.append(element[0])
    y.append(element[1])

In [133]:
print(len(TRAINING_DATA))
print(len(X))
print(len(y))

49892
49892
49892


In [134]:
X = np.array(X)  #.reshape(-1, IMG_SIZE,IMG_SIZE, 1)
y = np.array(y)

In [135]:
pickle.dump(X, open('X.pickle', 'wb'))
pickle.dump(y, open('y.pickle', 'wb'))

In [136]:
print("DONE!")

DONE!


In [137]:
print(X)

[[[209 230 238 ... 234 195 225]
  [217 210 214 ... 198 221 203]
  [209 205 222 ... 216 216 197]
  ...
  [232 236 241 ... 141  94  84]
  [226 225 236 ... 148 134 130]
  [228 224 231 ... 153 134 155]]

 [[ 38  42  37 ...  27  28  27]
  [ 39  44  39 ...  30  29  28]
  [ 43  43  39 ...  32  29  29]
  ...
  [ 33  34  36 ... 107  45  41]
  [ 31  36  37 ... 120  77  25]
  [ 34  36  37 ...  55  75  47]]

 [[ 43  44  45 ...  62  59  59]
  [ 40  39  39 ...  57  61  56]
  [ 41  40  40 ...  61  57  59]
  ...
  [199 190 177 ... 160 146 146]
  [213 214 211 ... 182 172 174]
  [211 194 198 ... 183 174 189]]

 ...

 [[ 49  48  52 ... 236 254 254]
  [ 42  45  49 ...  60  58  60]
  [ 36  34  47 ...  66  65  61]
  ...
  [ 58  58  58 ...  32  37  38]
  [ 55  63  62 ...  29  35  50]
  [ 46  51  55 ...  32  41  35]]

 [[110 121 106 ... 196 189 195]
  [117 109 103 ... 204 214 209]
  [137 117 122 ... 162 197 205]
  ...
  [ 65  50  82 ... 180 189 187]
  [ 85  84  77 ... 191 194 195]
  [ 88  96 125 ... 196 193 1